tests: components but dynamic list and utils + validations
ZupIT/beagle-backend-ts pull request #25
Opened 2022-03-25 03:53 UTC by arthurbleilzup

Signed-off-by: Arthur Bleil <arthur.bleil@zup.com.br>

Add: some missing validations for colors
Add: some missing validations for children

2022-03-25 17:49 UTC, Tiagoperes requested changes
General comments:

1. test every single property that the components can receive.
2. avoid maps with undefined values.
3. remove style processing from the tests, they should be unitary.

I did a review of `button.spec.tsx` and `utils.tsx`. Please read it, discuss if necessary, and update the other tests.

2022-03-25 17:49 UTC, Tiagoperes commented on components/__tests__/components/utils.tsx
> +  const expectedProperties = { style: fromSimpleStyle(style), ...properties }
An error in the processing of the styles would break all components tests, which is not great if our tests are supposed to be unitary.

Tip: mock `<StyledDefaultComponent>` to render a simple `component` with `properties = { ...options.properties, style }`. This way, you can isolate the tests to only check the component itself and not anything related to `StyledComponent`.

2022-03-25 17:49 UTC, Tiagoperes commented on components/__tests__/components/button.spec.tsx
> +      style: undefined,
you should test the style since this is a StyledComponent

2022-03-25 17:49 UTC, Tiagoperes commented on components/__tests__/components/button.spec.tsx
> +      children: undefined,
Any specific reason to pass undefined instead of omiting the key?

2022-03-25 17:49 UTC, Tiagoperes commented on components/__tests__/components/button.spec.tsx
> +      styleId: undefined,
since we're doing very simple tests, we should pass every property we can pass. If we don't, we miss testing if this specific property is being passed down.

example: if I remove the styleId from the components implementation, no test will break. It should break.

2022-03-25 17:49 UTC, Tiagoperes commented on components/__tests__/components/button.spec.tsx
> +        <Button id={id} enabled={props.enabled} onPress={props.onPress} styleId={props.styleId}>Click me!</Button>,
why not `<Button {...props}>`?

2022-03-28 13:06 UTC, Tiagoperes requested changes

2022-03-28 13:06 UTC, Tiagoperes commented on components/src/components/pull-to-refresh.tsx
> +  if (!children || (Array.isArray(children) && !children.length)) {
This is ok, no need to change. But if we start validating everything that is already validated by TS, our code will become very bloated, very fast.

If someone decides to bypass TS validation, it's not our problem.

This commentary is valid for every place you did runtime type validations.

2022-03-28 13:06 UTC, Tiagoperes commented on components/src/components/simple-form.tsx
> + *     <SimpleForm onSubmit={postAddress} onValidationError={errors.get('showAll').set(true)}>
The example was correct. The implementation was wrong.

When you notice cases like this, it is important to check the docs to see what the correct behavior is.
https://docs.usebeagle.io/v1.10/api/components/forms/simple-form/

Pls, fix both the implementation and test.

2022-03-28 19:00 UTC, arthurbleilzup commented on components/__tests__/tsconfig.json
> +      "@zup-it/beagle-backend-core/*": ["../core/src/*"]
Required for some actions and operations

2022-03-28 19:38 UTC, Tiagoperes approved these changes

2022-03-28 19:39 UTC, merged